---
title: "stl_lead_inequity"
author: "vic"
format: html
editor: visual
execute:
  echo: true
  warning: false
---

## Read in & Explore the data

```{r}
library(tidyverse)
library(janitor)
library(dplyr)
library(usethis)
```

```{r}
stl_lead <- read_csv(here::here("data", 
                                  "stl_blood_lead.csv")
                                  )

stl_lead <- janitor::clean_names(stl_lead)
```

```{r}
stl_lead_prop <- stl_lead %>% dplyr::mutate(prop_white = (white / total_pop) *100) 
```

### Create a Scatterplot

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated,
                                 y = prop_white), width = 2, height = 10) +
  geom_point(size = 0.5, 
             alpha = 1, 
             color = "purple")

stl_lead_plot

ggsave(here::here("figs", "stl_lead_plot.png"),
       width = 6,
       height = 5)
```

-   overall trend is that as the percent children of elevated blood pressure increases, the proportion of white decreases

### Create a histogram

```{r}
histogram_pctelevated <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(fill = "blue",
                 color = "blue")

histogram_pctelevated

ggsave(here::here("figs","histogram_pctevelated.jpg"))
                                  
```
